In [11]:
import pandas as pd
import numpy as np

In [3]:
pd.options.display.max_columns = 30

In [5]:
df = pd.read_csv(r"C:\Users\Murtaza\Downloads\police_project.csv\police_project.csv")

In [7]:
df

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [13]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   county_name         0 non-null      float64
 3   driver_gender       86406 non-null  object
 4   driver_age_raw      86414 non-null  float64
 5   driver_age          86120 non-null  float64
 6   driver_race         86408 non-null  object
 7   violation_raw       86408 non-null  object
 8   violation           86408 non-null  object
 9   search_conducted    91741 non-null  bool
 10  search_type         3196 non-null   object
 11  stop_outcome        86408 non-null  object
 12  is_arrested         86408 non-null  object
 13  stop_duration       86408 non-null  object
 14  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(3), object(10)
memory usage: 9.3+ MB

In [17]:
df.tail()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [21]:
df.columns

Index(['stop_date', 'stop_time', 'county_name', 'driver_gender',
       'driver_age_raw', 'driver_age', 'driver_race', 'violation_raw',
       'violation', 'search_conducted', 'search_type', 'stop_outcome',
       'is_arrested', 'stop_duration', 'drugs_related_stop'],
      dtype='object')

In [25]:
df.shape

(91741, 15)

In [27]:
df.describe()

       county_name  driver_age_raw    driver_age
count          0.0    86414.000000  86120.000000
mean           NaN     1970.491228     34.011333
std            NaN      110.914909     12.738564
min            NaN        0.000000     15.000000
25%            NaN     1967.000000     23.000000
50%            NaN     1980.000000     31.000000
75%            NaN     1987.000000     43.000000
max            NaN     8801.000000     99.000000

In [34]:
df.drop('county_name',axis=1,inplace=True)

In [36]:
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [38]:
df1 = df.copy()

In [40]:
df1.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [42]:
df1.drop('stop_date',axis=1,inplace=True)

In [44]:
df1.head()

,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [46]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_time           91741 non-null  object
 1   driver_gender       86406 non-null  object
 2   driver_age_raw      86414 non-null  float64
 3   driver_age          86120 non-null  float64
 4   driver_race         86408 non-null  object
 5   violation_raw       86408 non-null  object
 6   violation           86408 non-null  object
 7   search_conducted    91741 non-null  bool
 8   search_type         3196 non-null   object
 9   stop_outcome        86408 non-null  object
 10  is_arrested         86408 non-null  object
 11  stop_duration       86408 non-null  object
 12  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(2), object(9)
memory usage: 7.9+ MB

In [48]:
df1.drop(df1.iloc[[],[0,2,3,4,5,7,8,9,10,11,12]],axis=1,inplace=True)

In [50]:
df1.head()

  driver_gender violation
0             M  Speeding
1             M  Speeding
2             M  Speeding
3             M     Other
4             F  Speeding

In [54]:
df1.driver_gender.value_counts()

driver_gender
M    62895
F    23511
Name: count, dtype: int64

In [56]:
df.driver_gender.value_counts(normalize=True)

driver_gender
M    0.727901
F    0.272099
Name: proportion, dtype: float64

In [58]:
df.violation.value_counts()

violation
Speeding               48463
Moving violation       16224
Equipment              11020
Other                   4317
Registration/plates     3432
Seat belt               2952
Name: count, dtype: int64

In [62]:
df.violation.value_counts(normalize=True)

violation
Speeding               0.560862
Moving violation       0.187760
Equipment              0.127534
Other                  0.049961
Registration/plates    0.039719
Seat belt              0.034164
Name: proportion, dtype: float64

In [66]:
df1[df1.violation=='Speeding'].driver_gender.value_counts()

driver_gender
M    32979
F    15482
Name: count, dtype: int64

In [68]:
df1[df1.violation=='Speeding'].driver_gender.value_counts(normalize=True)

driver_gender
M    0.680527
F    0.319473
Name: proportion, dtype: float64

In [70]:
df1[df1.driver_gender=='M'].violation.value_counts()

violation
Speeding               32979
Moving violation       13020
Equipment               8533
Other                   3627
Registration/plates     2419
Seat belt               2317
Name: count, dtype: int64

In [72]:
df1[df1.driver_gender=='M'].violation.value_counts(normalize=True)

violation
Speeding               0.524350
Moving violation       0.207012
Equipment              0.135671
Other                  0.057668
Registration/plates    0.038461
Seat belt              0.036839
Name: proportion, dtype: float64

In [74]:
df1[df1.driver_gender=='F'].violation.value_counts()

violation
Speeding               15482
Moving violation        3204
Equipment               2487
Registration/plates     1013
Other                    690
Seat belt                635
Name: count, dtype: int64

In [76]:
df1[df1.driver_gender=='F'].violation.value_counts(normalize=True)

violation
Speeding               0.658500
Moving violation       0.136277
Equipment              0.105780
Registration/plates    0.043086
Other                  0.029348
Seat belt              0.027009
Name: proportion, dtype: float64

In [78]:
df2=df.copy()

In [80]:
df2.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [82]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   driver_gender       86406 non-null  object
 3   driver_age_raw      86414 non-null  float64
 4   driver_age          86120 non-null  float64
 5   driver_race         86408 non-null  object
 6   violation_raw       86408 non-null  object
 7   violation           86408 non-null  object
 8   search_conducted    91741 non-null  bool
 9   search_type         3196 non-null   object
 10  stop_outcome        86408 non-null  object
 11  is_arrested         86408 non-null  object
 12  stop_duration       86408 non-null  object
 13  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(2), object(10)
memory usage: 8.6+ MB

In [86]:
df2.drop(df2.iloc[[],[0,1,3,4,5,6,7,9,10,11,12,13]],axis=1,inplace=True)

In [88]:
df2.head()

  driver_gender  search_conducted
0             M             False
1             M             False
2             M             False
3             M             False
4             F             False

In [90]:
df2.driver_gender.value_counts()

driver_gender
M    62895
F    23511
Name: count, dtype: int64

In [96]:
df2.search_conducted.value_counts()

search_conducted
False    88545
True      3196
Name: count, dtype: int64

In [98]:
df2[df2.search_conducted==False].driver_gender.value_counts()

driver_gender
M    60170
F    23040
Name: count, dtype: int64

In [100]:
df2[df2.search_conducted==True].driver_gender.value_counts()

driver_gender
M    2725
F     471
Name: count, dtype: int64

In [102]:
df3=df.copy()

In [104]:
df3.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [106]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   driver_gender       86406 non-null  object
 3   driver_age_raw      86414 non-null  float64
 4   driver_age          86120 non-null  float64
 5   driver_race         86408 non-null  object
 6   violation_raw       86408 non-null  object
 7   violation           86408 non-null  object
 8   search_conducted    91741 non-null  bool
 9   search_type         3196 non-null   object
 10  stop_outcome        86408 non-null  object
 11  is_arrested         86408 non-null  object
 12  stop_duration       86408 non-null  object
 13  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(2), object(10)
memory usage: 8.6+ MB

In [110]:
df3.drop(df3.iloc[[],[0,1,2,3,4,5,6,9,10,11,12,13]],axis=1,inplace=True)

In [112]:
df3.head()

  violation  search_conducted
0  Speeding             False
1  Speeding             False
2  Speeding             False
3     Other             False
4  Speeding             False

In [114]:
df3[df3.search_conducted==True].violation.value_counts()

violation
Speeding               957
Moving violation       895
Equipment              704
Registration/plates    334
Other                  210
Seat belt               96
Name: count, dtype: int64

In [116]:
df3[df3.search_conducted==False].violation.value_counts()

violation
Speeding               47506
Moving violation       15329
Equipment              10316
Other                   4107
Registration/plates     3098
Seat belt               2856
Name: count, dtype: int64

In [118]:
df3[df3.search_conducted==False].violation.value_counts(normalize=True)

violation
Speeding               0.570903
Moving violation       0.184216
Equipment              0.123973
Other                  0.049356
Registration/plates    0.037230
Seat belt              0.034322
Name: proportion, dtype: float64

In [120]:
df3[df3.search_conducted==True].violation.value_counts(normalize=True)

violation
Speeding               0.299437
Moving violation       0.280038
Equipment              0.220275
Registration/plates    0.104506
Other                  0.065707
Seat belt              0.030038
Name: proportion, dtype: float64

In [122]:
df4=df.copy()

In [125]:
df4.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [127]:
df4.drop(df4.iloc[[],[0,1,3,4,5,6,9,10,11,12,13]],axis=1,inplace=True)

In [129]:
df4.head()

  driver_gender violation  search_conducted
0             M  Speeding             False
1             M  Speeding             False
2             M  Speeding             False
3             M     Other             False
4             F  Speeding             False

In [131]:
df4[df4.search_conducted==True].violation.value_counts()

violation
Speeding               957
Moving violation       895
Equipment              704
Registration/plates    334
Other                  210
Seat belt               96
Name: count, dtype: int64

In [133]:
df4.groupby(['driver_gender','violation']).search_conducted.value_counts()

driver_gender  violation            search_conducted
F              Equipment            False                2381
                                    True                  106
               Moving violation     False                3088
                                    True                  116
               Other                False                 651
                                    True                   39
               Registration/plates  False                 946
                                    True                   67
               Seat belt            False                 627
                                    True                    8
               Speeding             False               15347
                                    True                  135
M              Equipment            False                7935
                                    True                  598
               Moving violation     False               12241
                                    True                  779
               Other                False                3456
                                    True                  171
               Registration/plates  False                2152
                                    True                  267
               Seat belt            False                2229
                                    True                   88
               Speeding             False               32157
                                    True                  822
Name: count, dtype: int64

In [135]:
df4.groupby(['violation','search_conducted']).driver_gender.value_counts()

violation            search_conducted  driver_gender
Equipment            False             M                 7935
                                       F                 2381
                     True              M                  598
                                       F                  106
Moving violation     False             M                12241
                                       F                 3088
                     True              M                  779
                                       F                  116
Other                False             M                 3456
                                       F                  651
                     True              M                  171
                                       F                   39
Registration/plates  False             M                 2152
                                       F                  946
                     True              M                  267
                                       F                   67
Seat belt            False             M                 2229
                                       F                  627
                     True              M                   88
                                       F                    8
Speeding             False             M                32157
                                       F                15347
                     True              M                  822
                                       F                  135
Name: count, dtype: int64

In [137]:
df5=df.copy()

In [139]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   driver_gender       86406 non-null  object
 3   driver_age_raw      86414 non-null  float64
 4   driver_age          86120 non-null  float64
 5   driver_race         86408 non-null  object
 6   violation_raw       86408 non-null  object
 7   violation           86408 non-null  object
 8   search_conducted    91741 non-null  bool
 9   search_type         3196 non-null   object
 10  stop_outcome        86408 non-null  object
 11  is_arrested         86408 non-null  object
 12  stop_duration       86408 non-null  object
 13  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(2), object(10)
memory usage: 8.6+ MB

In [143]:
df5.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [147]:
df.shape

(91741, 14)

In [149]:
pd.crosstab(
    df['search_conducted'],
    df['is_arrested'],
    normalize='index'
)*100

is_arrested           False      True
search_conducted
False             97.793587   2.206413
True              65.801001  34.198999

In [151]:
pd.crosstab(
    df['driver_race'],
    df['search_conducted'],
    normalize='index'
)*100

search_conducted      False     True
driver_race
Asian             97.742364  2.257636
Black             93.547860  6.452140
Hispanic          93.857158  6.142842
Other             98.750000  1.250000
White             97.155636  2.844364

In [155]:
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False